### ISSUE TITLE
ALIX bliz my brother latest turnip zink exagear bliz 🥹🥹🥹

### ISSUE THREAD

**Issue by Azedin1111** [alexvorxx/zink-xlib-termux#1]
ALIX bliz my brother latest turnip.zink exagear bliz 🥹🥹🥹

**Comment by Azedin1111** [comment]
my brother latest turnip zink on exagear Please 🙂🙂🙂

**Comment by alexvorxx** [comment]
> my brother latest turnip zink on exagear Please 🙂🙂🙂

I still can’t build Turnip, errors appear during building

**Comment by Azedin1111** [comment]
> > my brother latest turnip zink on exagear Please 🙂🙂🙂
> 
> I still can’t build Turnip, errors appear during building

😔😔😔😔 Ok thanks

**Comment by Azedin1111** [comment]
🥺🥺🥺🥺🥺

**Comment by alexvorxx** [comment]
> 🥺🥺🥺🥺🥺

As soon as I can compile the latest Turnip, I will upload it immediately.

**Comment by Azedin1111** [comment]
> > 🥺🥺🥺🥺🥺
> 
> As soon as I can compile the latest Turnip, I will upload it immediately.

thank you 😊😊😊

**Comment by alexvorxx** [comment]
> > > 🥺🥺🥺🥺🥺
> > 
> > 
> > As soon as I can compile the latest Turnip, I will upload it immediately.
> 
> thank you 😊😊😊

Done
https://github.com/alexvorxx/Zink-Mesa-Xlib/releases/tag/v0.0.7beta

**Comment by Azedin1111** [comment]
> > > > 🥺🥺🥺🥺🥺
> > > 
> > > 
> > > As soon as I can compile the latest Turnip, I will upload it immediately.
> > 
> > 
> > thank you 😊😊😊
> 
> Done https://github.com/alexvorxx/Zink-Mesa-Xlib/releases/tag/v0.0.7beta

thank you my brother
