### ISSUE TITLE
Запуск hangover 9.3

### ISSUE THREAD

**Issue by qwertypower** [alexvorxx/zink-xlib-termux#20]
Привет, а как собственно запустить hangover? Если сделать по инструкции с релиза, то вайн не может найти устройство вывода графики. Ставил на Poco F3. Можно ли подробную инструкцию про запуск?

**Comment by alexvorxx** [comment]
> Привет, а как собственно запустить hangover? Если сделать по инструкции с релиза, то вайн не может найти устройство вывода графики. Ставил на Poco F3. Можно ли подробную инструкцию про запуск?

Точно установлены драйверы графики? Пробовали запускать glxinfo, glxgears, что выводит при этом?

**Comment by qwertypower** [comment]
> > Привет, а как собственно запустить hangover? Если сделать по инструкции с релиза, то вайн не может найти устройство вывода графики. Ставил на Poco F3. Можно ли подробную инструкцию про запуск?
> 
> Точно установлены драйверы графики? Пробовали запускать glxinfo, glxgears, что выводит при этом?

По инструкции ставил всё по порядку, но вывод не идёт.

![Screenshot_2024-05-02-14-48-39-550_com termux](https://github.com/alexvorxx/zink-xlib-termux/assets/11279860/656f1d49-66be-4aaa-b692-573541284eaa)
![Screenshot_2024-05-02-14-48-55-976_com termux](https://github.com/alexvorxx/zink-xlib-termux/assets/11279860/9a85391f-6645-4902-a3cd-4c003463b00a)

**Comment by alexvorxx** [comment]
> > > Привет, а как собственно запустить hangover? Если сделать по инструкции с релиза, то вайн не может найти устройство вывода графики. Ставил на Poco F3. Можно ли подробную инструкцию про запуск?
> > 
> > 
> > Точно установлены драйверы графики? Пробовали запускать glxinfo, glxgears, что выводит при этом?
> 
> По инструкции ставил всё по порядку, но вывод не идёт.
> 
> ![Screenshot_2024-05-02-14-48-39-550_com termux](https://private-user-images.githubusercontent.com/11279860/327418286-656f1d49-66be-4aaa-b692-573541284eaa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTE0NzksIm5iZiI6MTcxNDY1MTE3OSwicGF0aCI6Ii8xMTI3OTg2MC8zMjc0MTgyODYtNjU2ZjFkNDktNjZiZS00YWFhLWI2OTItNTczNTQxMjg0ZWFhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDExNTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZDZhZTIxYTQ3M2E4NTI3ZDA3NzUwNWVmZWU3MTUxMDFhNjk4ZDcwMmMyOGY0NzdkMjc3N2NhM2UxNmNjM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Q4zpBucL4R7ep0XTELOnekWUSsFj42ZcLdKcjU0wTo) ![Screenshot_2024-05-02-14-48-55-976_com termux](https://private-user-images.githubusercontent.com/11279860/327418297-9a85391f-6645-4902-a3cd-4c003463b00a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTE0NzksIm5iZiI6MTcxNDY1MTE3OSwicGF0aCI6Ii8xMTI3OTg2MC8zMjc0MTgyOTctOWE4NTM5MWYtNjY0NS00OTAyLWEzY2QtNGMwMDM0NjNiMDBhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDExNTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4Zjg3ZWNjYTI5MTdmNGZhZGY0YWQ5ZDNhM2M1NjhhMTRmMTRlMWZhMGM2NjQ5MjExZDIwNWM1MjRiODNlNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XJrT_uhiNQG18H0-fkTZDq2gZaXMxI0b5X29qhkXoEE)

Сначала нужно запустить X-сервер.

termux-x11 :0 &>/dev/null &
export DISPLAY=:0

Затем указать, что нужно использовать Zink.

export GALLIUM_DRIVER=zink
export MESA_LOADER_DRIVER_OVERRIDE=zink

**Comment by qwertypower** [comment]
Да, супер, заработало, большое спасибо!
Но эти моменты стоило бы описать в релизе hangover...
