### ISSUE TITLE
Finally Zink working in mali g57 android with vulkan 1.1 but still has some issues which can be solved by zink-xlib-termux

### ISSUE THREAD

**Issue by Githubpradip** [alexvorxx/zink-xlib-termux#23]
@alexvorxx 
Hello I installed hangover from termux tur-repo and install mesa-vulkan-icd-wrapper by @xMeM from https://github.com/xMeM/termux-packages/actions/runs/11756819746
and copy lib* from here https://github.com/alexvorxx/hangover-termux/releases/download/9.5/zink-xlib-termux-15.03.24_build.zip
And then I can run cubemap and also dolphinvs in hangover wine but cannot run SphereMap and Gpu Caps Viewer of other demonstrations in Mali g57 android device 

https://github.com/user-attachments/assets/1d9b46b7-da26-43cf-aad7-f8b2f8b10f84
 
Pls provide me the packages to fix this

**Comment by alexvorxx** [comment]
You may try other releases of Zink:
https://github.com/alexvorxx/zink-xlib-termux/releases

**Comment by Githubpradip** [comment]
> You may try other releases of Zink: https://github.com/alexvorxx/zink-xlib-termux/releases

I tried another package and it worked but still gpu caps viewer vulkan demos are not working
![Screenshot_2024-11-12-20-40-32-274_com termux x11](https://github.com/user-attachments/assets/6c1f67ee-c5b8-4ad1-8d1f-768a21a2ab5b)

Pls tell solution to fix it

**Comment by alexvorxx** [comment]
> > You may try other releases of Zink: https://github.com/alexvorxx/zink-xlib-termux/releases
> 
> I tried another package and it worked but still gpu caps viewer vulkan demos are not working !
> Pls tell solution to fix it

Vulkan demos work for me on **GPU Caps Viewer 1.63.0.0** only, but previous versions do not work.

**Comment by Githubpradip** [comment]
https://github.com/user-attachments/assets/1f58e8ed-4be2-4727-9bf8-109cee9437f3

> > > You may try other releases of Zink: https://github.com/alexvorxx/zink-xlib-termux/releases
> > 
> > 
> > I tried another package and it worked but still gpu caps viewer vulkan demos are not working !
> > Pls tell solution to fix it
> 
> Vulkan demos work for me on **GPU Caps Viewer 1.63.0.0** only, but previous versions do not work.

That works with MESA_VK_WSI_DEBUG=sw 
But then I got a problem with VK_EXT_map_memory_placed problem in wine
Which can be fixed by modifying libvulkan_wrapper.so by @xMeM can you update that with VK_EXT_map_memory_placed extension fixed

Wine shows this error
"wine_vkMapMemory2KHR returned mapping 0x5efe765000 does not fit 32-bit pointer"

**Comment by Githubpradip** [comment]
Problem fixed

**Comment by agaHa175** [comment]
> Problem fixed

Ahh I guess that's a little bit late but how do you fix the problem? Because I have the same GPU and the same problem 🤡
