### ISSUE TITLE
Need zink-xlib-termux (arm 32-bit) version for wine termux

### ISSUE THREAD

**Issue by Githubpradip** [alexvorxx/zink-xlib-termux#25]
Finally vulkan-demos run in box86 wine
 (termux 32-bit prefix) in Mali G57
but still has some issues due to opengl is not upgraded if you give zink-xlib-termux .so files for {arm (32-bit)} I can test dx9 or dxvk games in mali.
So kindly provide these

https://github.com/user-attachments/assets/1342df7b-5ee6-4e88-87c8-ad1379d5c067

**Comment by alexvorxx** [comment]
> but still has some issues due to opengl is not upgraded if you give zink-xlib-termux .so files for {arm (32-bit)} I can test dx9 or dxvk games in mali.

Sorry, but I can't compile libraries for 32 bit arm termux. The arm64 termux version doesn't work for you?

**Comment by Githubpradip** [comment]
> > but still has some issues due to opengl is not upgraded if you give zink-xlib-termux .so files for {arm (32-bit)} I can test dx9 or dxvk games in mali.
> 
> Sorry, but I can't compile libraries for 32 bit arm termux. The arm64 termux version doesn't work for you?.
